// Build src/write-tiers.js from an app's published actions (PeerLoop: testdata/contract/api/actions.json,
// the same list its GET /api/actions answers), so the wallet never takes a write's tier from the page.
//
//   node scripts/write-tiers.mjs [actions.json]     (default: ../../p2p/testdata/contract/api/actions.json)
//
// Regenerate it, then the bundles, whenever the app's actions change.
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const from = resolve(process.argv[2] ?? join(root, '../../p2p/testdata/contract/api/actions.json'))
const { actions } = JSON.parse(readFileSync(from, 'utf8'))
const tiers = {}
for (const { kind, tier } of actions) {
  if (typeof kind !== 'string' || !['prompted', 'silent'].includes(tier)) throw new Error(`not an action: ${JSON.stringify({ kind, tier })}`)
  tiers[kind] = tier
}
const body = Object.keys(tiers).sort().map((k) => `  '${k}': '${tiers[k]}'`).join(',\n')
writeFileSync(join(root, 'src/write-tiers.js'), `// GENERATED by scripts/write-tiers.mjs from PeerLoop's testdata/contract/api/actions.json — do not edit.
// Each write kind's tier: 'silent' kinds are signed without asking under the keep-signed-in grant;
// the wallet always asks about 'prompted' kinds, and about any kind not listed here.
export const WRITE_TIERS = Object.freeze({
${body}
})
`)
console.log(`src/write-tiers.js: ${Object.keys(tiers).length} kinds from ${from}`)
