// GENERATED by scripts/write-tiers.mjs from PeerLoop's testdata/contract/api/actions.json — do not edit.
// Each write kind's tier: 'silent' kinds are signed without asking under the keep-signed-in grant;
// the wallet always asks about 'prompted' kinds, and about any kind not listed here.
export const WRITE_TIERS = Object.freeze({
  'block': 'prompted',
  'call.ring': 'silent',
  'channel-request.decide': 'prompted',
  'channel.create': 'silent',
  'channel.mute': 'silent',
  'channel.patch': 'prompted',
  'channel.request': 'silent',
  'contact.decide': 'silent',
  'contact.remove': 'silent',
  'contact.request': 'silent',
  'contact.withdraw': 'silent',
  'invite.accept': 'silent',
  'invite.create': 'silent',
  'me.patch': 'silent',
  'member.remove': 'prompted',
  'member.role': 'prompted',
  'message.delete': 'silent',
  'message.edit': 'silent',
  'message.post': 'silent',
  'pin': 'silent',
  'push.subscribe': 'silent',
  'push.unsubscribe': 'silent',
  'reaction.add': 'silent',
  'reaction.remove': 'silent',
  'registration.decide': 'prompted',
  'unblock': 'prompted',
  'unpin': 'silent',
  'user.role': 'prompted'
})
